/** Local index for claim.sourceIds (docs/RESEARCH.md §4). External pages need a network connection. */
export type SourceEntry = { id: string; title: string; note: string; url: string | null; titleEn?: string; noteEn: string };

export const SOURCES: readonly SourceEntry[] = [
  { id: 'G01', title: 'The Digital Ambler：How to Construct the Shield Chart',
    note: '盾盤構造的實務說明；用於算法與位置關係。',
    noteEn: 'A practical guide to building the shield chart; used for the arithmetic and how positions relate.',
    url: 'https://digitalambler.com/2020/05/08/how-to-construct-the-shield-chart-of-geomancy/' },
  { id: 'G02', title: 'The Digital Ambler：House Chart from Shield Chart',
    note: '入宮方法與歷史討論；本產品選擇順序入宮。',
    noteEn: 'Ways of placing figures into houses and their history; this App uses sequential houses by default.',
    url: 'https://digitalambler.com/2020/05/04/on-making-the-house-chart-from-the-shield-chart/' },
  { id: 'G03', title: 'Geomancy 歷史刊文（1918 刊文影本）', titleEn: 'Geomancy (facsimile of a 1918 periodical article)',
    note: '十六象圖式的參照。',
    noteEn: 'Reference for the dot patterns of the sixteen figures.',
    url: 'https://www.100thmonkeypress.com/biblio/acrowley/periodicals/geomancy/geomancy.pdf' },
  { id: 'G04', title: 'Elizabeth Bennett／Princeton：Medieval Geomancy 步驟', titleEn: 'Elizabeth Bennett / Princeton: Medieval Geomancy, the steps',
    note: '地占步驟與解讀背景；不是本產品中文文案的原文。',
    noteEn: 'The steps of geomancy and background for reading; not the source text of this App’s wording.',
    url: 'https://www.princeton.edu/~ezb/geomancy/geostep.html' },
  { id: 'G05', title: 'Elizabeth Bennett／Princeton：The Geomantic Figures', titleEn: 'Elizabeth Bennett / Princeton: The Geomantic Figures',
    note: '圖式與名稱的歷史變體。',
    noteEn: 'Historical variants of the patterns and names.',
    url: 'https://www.princeton.edu/~ezb/geomancy/figures.html' },
  { id: 'G06', title: 'The Digital Ambler：More About Geomantic Perfection',
    note: '四種成事關係（同象、接合、轉移、傳遞）與不成事的定義；進階解讀依此計算。',
    noteEn: 'Definitions of the four ways of perfection (occupation, conjunction, mutation, translation) and of denial; the advanced reading follows them.',
    url: 'https://digitalambler.com/2014/06/05/more-about-geomantic-perfection/' },
  { id: 'G07', title: 'The Digital Ambler：Via Puncti（點之道）', titleEn: 'The Digital Ambler: Via Puncti (the Way of the Points)',
    note: '點之道的追溯規則：從裁判的火行往上，經證人、姪象到母象或女象；兩點時可能分岔或中斷。',
    noteEn: 'How to trace the Way of the Points: from the Judge’s fire line up through the Witnesses and Nieces to the Mothers or Daughters; it may split or break.',
    url: 'https://digitalambler.com/2012/12/18/de-geomanteia-via-puncti-follow-the-yellow-brick-road/' },
  { id: 'G08', title: 'John Michael Greer：The Art and Practice of Geomancy（2009）', titleEn: 'John Michael Greer: The Art and Practice of Geomancy (2009)',
    note: '書目。宮位相位（六分、四分、三分、對分）與象在多宮重現的常見西方實務；本案依一般占星宮距整理規則，未能直接核對原書頁碼。',
    noteEn: 'Bibliography. Common Western practice for house aspects (sextile, square, trine, opposition) and figures recurring in several houses; the rules here follow ordinary astrological house distances, not checked against the book’s pages.',
    url: null },
  { id: 'G09', title: 'The Digital Ambler：Sum of their Parts（十六象的行星合成）', titleEn: 'The Digital Ambler: Sum of their Parts (planetary syntheses of the figures)',
    note: '十六象兩兩配給七個行星與月交點（龍首、龍尾）；學習區的行星對應依此表。星座與元素各傳統差異大，本產品未採用。',
    noteEn: 'Pairs the sixteen figures with the seven planets and the lunar nodes (Caput and Cauda Draconis); the planets in the learning area follow this table.',
    url: 'https://digitalambler.com/2020/03/30/sum-of-their-parts-the-planetary-syntheses-of-the-geomantic-figures/' },
  { id: 'G10', title: 'The Digital Ambler：On Halted Geomancy Charts（停止盤）', titleEn: 'The Digital Ambler: On Halted Geomancy Charts',
    note: '舊歐洲文本中「第一母象為紅或龍尾就捨棄此盤」的禁例，以及天氣、身心狀態、誠意等起卦條件；作者本人表示現在多半不遵守。',
    noteEn: 'The old European rule of discarding a chart whose First Mother is Rubeus or Cauda Draconis, and conditions such as weather, state of mind and sincerity; the author says he mostly does not follow them now.',
    url: 'https://digitalambler.com/2018/01/31/on-halted-geomancy-charts/' },
  { id: 'G11', title: 'The Digital Ambler：On Geomantic Figures, Zodiac Signs, and Lunar Mansions',
    note: '十六象的星座對照：Agrippa 依行星推導的方法，與 Gerard of Cremona〈On Astronomical Geomancy〉依月宿推導的方法；本產品照原表並列兩者。',
    noteEn: 'Zodiac signs for the figures: Agrippa’s method from the planets and Gerard of Cremona’s from the lunar mansions; this App lists both as given.',
    url: 'https://digitalambler.com/2015/04/03/on-geomantic-figures-zodiac-signs-and-lunar-mansions/' },
  { id: 'G12', title: 'The Digital Ambler：On Elemental Assignments of the Geomantic Figures',
    note: '七份文獻的元素對照表（Cattan 1591、Agrippa 1655 三種、Heydon 1663、Fludd 1687、Case 1697）；本產品照原表列出，不修正其中看似不一致之處。',
    noteEn: 'Elements of the figures in seven sources (Cattan 1591, three in Agrippa 1655, Heydon 1663, Fludd 1687, Case 1697); listed as given, apparent inconsistencies left as they are.',
    url: 'https://digitalambler.com/2018/01/14/on-elemental-assignments-of-the-geomantic-figures/' },
  { id: 'G13', title: 'Golden Dawn：Geomancy（Frater D.D.C.F.，Thelemagick Library 轉錄）', titleEn: 'Golden Dawn: Geomancy (Frater D.D.C.F., Thelemagick Library transcription)',
    note: '黃金黎明會的地占講義。第一到第十二個象依序放進第 10、1、4、7、11、2、5、8、12、3、6、9 宮；本產品的 Golden Dawn 入宮依此，並與 G02 核對一致。講義對調和者的定義（裁判＋問題宮的象）與本產品不同，本產品未採用。',
    noteEn: 'The Golden Dawn geomancy paper. The first to twelfth figures go into houses 10, 1, 4, 7, 11, 2, 5, 8, 12, 3, 6, 9; this App’s Golden Dawn houses follow it and agree with G02. Its Reconciler (Judge + the figure of the question house) differs from this App’s and is not used.',
    url: 'https://www.tarrdaniel.com/documents/Thelemagick/gd/publication/english/Geomancy.html' },
  { id: 'E01', title: '地占沙盤原創編輯草稿', titleEn: 'This App’s original editorial drafts',
    note: '本產品自行撰寫的中文象義摘要與反思提示。內容狀態為編輯草稿，尚未經外部地占專家逐條審校。',
    noteEn: 'Summaries of meanings and reflection prompts written for this App, in Chinese and English. Editorial drafts, not yet reviewed line by line by an outside geomancy expert.',
    url: null },
];
export const sourceById = (id: string): SourceEntry | undefined => SOURCES.find(s => s.id === id);
/** Title and note in the interface language; titles already in English stay as they are. */
export const sourceText = (entry: SourceEntry, lang: 'zh-TW' | 'en') =>
  lang === 'en' ? { title: entry.titleEn ?? entry.title.replace('：', ': '), note: entry.noteEn } : { title: entry.title, note: entry.note };
