/** Local index for claim.sourceIds (docs/RESEARCH.md §4). External pages need a network connection. */
export type SourceEntry = { id: string; title: string; note: string; url: string | null };

export const SOURCES: readonly SourceEntry[] = [
  { id: 'G01', title: 'The Digital Ambler：How to Construct the Shield Chart',
    note: '盾盤構造的實務說明；用於算法與位置關係。',
    url: 'https://digitalambler.com/2020/05/08/how-to-construct-the-shield-chart-of-geomancy/' },
  { id: 'G02', title: 'The Digital Ambler：House Chart from Shield Chart',
    note: '入宮方法與歷史討論；本產品選擇順序入宮。',
    url: 'https://digitalambler.com/2020/05/04/on-making-the-house-chart-from-the-shield-chart/' },
  { id: 'G03', title: 'Geomancy 歷史刊文（1918 刊文影本）',
    note: '十六象圖式的參照。',
    url: 'https://www.100thmonkeypress.com/biblio/acrowley/periodicals/geomancy/geomancy.pdf' },
  { id: 'G04', title: 'Elizabeth Bennett／Princeton：Medieval Geomancy 步驟',
    note: '地占步驟與解讀背景；不是本產品中文文案的原文。',
    url: 'https://www.princeton.edu/~ezb/geomancy/geostep.html' },
  { id: 'G05', title: 'Elizabeth Bennett／Princeton：The Geomantic Figures',
    note: '圖式與名稱的歷史變體。',
    url: 'https://www.princeton.edu/~ezb/geomancy/figures.html' },
  { id: 'G06', title: 'The Digital Ambler：More About Geomantic Perfection',
    note: '四種成事關係（同象、接合、轉移、傳遞）與不成事的定義；進階解讀依此計算。',
    url: 'https://digitalambler.com/2014/06/05/more-about-geomantic-perfection/' },
  { id: 'G07', title: 'The Digital Ambler：Via Puncti（點之道）',
    note: '點之道的追溯規則：從裁判的火行往上，經證人、姪象到母象或女象；兩點時可能分岔或中斷。',
    url: 'https://digitalambler.com/2012/12/18/de-geomanteia-via-puncti-follow-the-yellow-brick-road/' },
  { id: 'G08', title: 'John Michael Greer：The Art and Practice of Geomancy（2009）',
    note: '書目。宮位相位（六分、四分、三分、對分）與象在多宮重現的常見西方實務；本案依一般占星宮距整理規則，未能直接核對原書頁碼。',
    url: null },
  { id: 'G09', title: 'The Digital Ambler：Sum of their Parts（十六象的行星合成）',
    note: '十六象兩兩配給七個行星與月交點（龍首、龍尾）；學習區的行星對應依此表。星座與元素各傳統差異大，本產品未採用。',
    url: 'https://digitalambler.com/2020/03/30/sum-of-their-parts-the-planetary-syntheses-of-the-geomantic-figures/' },
  { id: 'G10', title: 'The Digital Ambler：On Halted Geomancy Charts（停止盤）',
    note: '舊歐洲文本中「第一母象為紅或龍尾就捨棄此盤」的禁例，以及天氣、身心狀態、誠意等起卦條件；作者本人表示現在多半不遵守。',
    url: 'https://digitalambler.com/2018/01/31/on-halted-geomancy-charts/' },
  { id: 'G11', title: 'The Digital Ambler：On Geomantic Figures, Zodiac Signs, and Lunar Mansions',
    note: '十六象的星座對照：Agrippa 依行星推導的方法，與 Gerard of Cremona〈On Astronomical Geomancy〉依月宿推導的方法；本產品照原表並列兩者。',
    url: 'https://digitalambler.com/2015/04/03/on-geomantic-figures-zodiac-signs-and-lunar-mansions/' },
  { id: 'G12', title: 'The Digital Ambler：On Elemental Assignments of the Geomantic Figures',
    note: '七份文獻的元素對照表（Cattan 1591、Agrippa 1655 三種、Heydon 1663、Fludd 1687、Case 1697）；本產品照原表列出，不修正其中看似不一致之處。',
    url: 'https://digitalambler.com/2018/01/14/on-elemental-assignments-of-the-geomantic-figures/' },
  { id: 'E01', title: '地占沙盤原創編輯草稿',
    note: '本產品自行撰寫的中文象義摘要與反思提示。內容狀態為編輯草稿，尚未經外部地占專家逐條審校。',
    url: null },
];
export const sourceById = (id: string): SourceEntry | undefined => SOURCES.find(s => s.id === id);
